# Infra/render.yaml
services:
  - type: web
    name: tda-api
    env: python
    plan: free
    rootDir: Backend
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: APP_VERSION
        value: "1.0.0"
      - key: DATABASE_URL
        sync: false           # set in Render dashboard
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: "gpt-4.1-mini"
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_PLACES_LANGUAGE
        value: "nl"
      - key: GOOGLE_PLACES_REGION
        value: "NL"
      - key: CLASSIFY_MIN_CONF
        value: "0.80"
      - key: MONITOR_MAX_PER_RUN
        value: "200"
      # Alerting thresholds per TDA-20
      - key: ALERT_CHECK_INTERVAL_SECONDS
        value: "60"
      - key: ALERT_ERR_RATE_THRESHOLD
        value: "0.10"
      - key: ALERT_GOOGLE429_THRESHOLD
        value: "5"
      - key: ALERT_ERR_RATE_WINDOW_MINUTES
        value: "60"
      - key: ALERT_GOOGLE429_WINDOW_MINUTES
        value: "60"
      - key: ALERT_WEBHOOK_URL
        sync: false           # optional (Slack/Teams)
      - key: ALERT_CHANNEL
        value: "ops"          # optional

# Cron jobs (Render) – draaien het Backend/worker-ecosysteem
# Zie: Discovery/Verification/Monitor/Alert bots en Freshness Policy. 
# TDA-7/8/11/16/20 beschrijven gedrag, retries, en drempels.
# Discovery: wekelijks; Verification: elke 30 min; Monitor: elk uur; Alert: elke 5 min.
# Pas schema en flags aan op basis van jouw productiestrategie.
cronJobs:
  - name: discovery-bot-weekly
    schedule: "0 2 * * 6"   # Za 02:00 CET
    env: python
    plan: free
    rootDir: Backend
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: >
      python -m app.workers.discovery_bot
      --city rotterdam
      --categories bakery,restaurant,supermarket
      --nearby-radius-m 1000
      --grid-span-km 12
      --max-per-cell-per-category 20
      --inter-call-sleep-s 0.15
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_PLACES_LANGUAGE
        value: "nl"
      - key: GOOGLE_PLACES_REGION
        value: "NL"

  - name: verification-bot-30min
    schedule: "*/30 * * * *"
    env: python
    plan: free
    rootDir: Backend
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: >
      python -m app.workers.verification_bot
      --limit 300
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: "gpt-4.1-mini"
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_PLACES_LANGUAGE
        value: "nl"
      - key: GOOGLE_PLACES_REGION
        value: "NL"
      - key: CLASSIFY_MIN_CONF
        value: "0.80"

  - name: monitor-bot-hourly
    schedule: "0 * * * *"
    env: python
    plan: free
    rootDir: Backend
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: >
      python -m app.workers.monitor_bot
      --limit 200
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: MONITOR_MAX_PER_RUN
        value: "200"

  - name: alert-bot-5min
    schedule: "*/5 * * * *"
    env: python
    plan: free
    rootDir: Backend
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: >
      python -m app.workers.alert_bot
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ALERT_CHECK_INTERVAL_SECONDS
        value: "60"
      - key: ALERT_ERR_RATE_THRESHOLD
        value: "0.10"
      - key: ALERT_GOOGLE429_THRESHOLD
        value: "5"
      - key: ALERT_ERR_RATE_WINDOW_MINUTES
        value: "60"
      - key: ALERT_GOOGLE429_WINDOW_MINUTES
        value: "60"
      - key: ALERT_WEBHOOK_URL
        sync: false
      - key: ALERT_CHANNEL
        value: "ops"
