name: TDA Daily DB Cleanup

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  cleanup-db:
    name: Cleanup Supabase ai_logs
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client

      - name: Clean old ai_logs and vacuum
        shell: bash
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          set -euo pipefail

          if [[ -z "${DATABASE_URL:-}" ]]; then
            echo "DATABASE_URL is not set" >&2
            exit 1
          fi

          # Ensure sslmode=require is present
          if [[ "$DATABASE_URL" == *"sslmode="* ]]; then
            EFFECTIVE_DATABASE_URL="$DATABASE_URL"
          elif [[ "$DATABASE_URL" == *"?"* ]]; then
            EFFECTIVE_DATABASE_URL="${DATABASE_URL}&sslmode=require"
          else
            EFFECTIVE_DATABASE_URL="${DATABASE_URL}?sslmode=require"
          fi

          SQL=$'DELETE FROM public.ai_logs\nWHERE id IN (\n  SELECT id\n  FROM public.ai_logs\n  WHERE created_at < NOW() - INTERVAL \'3 days\'\n  ORDER BY created_at ASC\n  OFFSET 5000\n);\nVACUUM FULL public.ai_logs;\nANALYZE public.ai_logs;'
          echo "$SQL" | psql --no-psqlrc --set ON_ERROR_STOP=1 --quiet "$EFFECTIVE_DATABASE_URL"

          echo "✅ Old ai_logs cleaned (older than 3 days) and compacted successfully"